// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxINKxn-a2WDHr5-y7xgRVzTfWxEFUBVA',
    appId: '1:926118704354:web:0eb42054e830df36779abb',
    messagingSenderId: '926118704354',
    projectId: 'recipeappflutter-17c08',
    authDomain: 'recipeappflutter-17c08.firebaseapp.com',
    storageBucket: 'recipeappflutter-17c08.firebasestorage.app',
    measurementId: 'G-3D3KTST1KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tK7ybM7lKwVsin5tMGOCVMI_TU1YcU0',
    appId: '1:926118704354:android:835641713d6418c9779abb',
    messagingSenderId: '926118704354',
    projectId: 'recipeappflutter-17c08',
    storageBucket: 'recipeappflutter-17c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqqVYvvT1EtuoxrBhNdRplSkJZnZ2VqA',
    appId: '1:926118704354:ios:05a321bc8049bd13779abb',
    messagingSenderId: '926118704354',
    projectId: 'recipeappflutter-17c08',
    storageBucket: 'recipeappflutter-17c08.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcqqVYvvT1EtuoxrBhNdRplSkJZnZ2VqA',
    appId: '1:926118704354:ios:05a321bc8049bd13779abb',
    messagingSenderId: '926118704354',
    projectId: 'recipeappflutter-17c08',
    storageBucket: 'recipeappflutter-17c08.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxINKxn-a2WDHr5-y7xgRVzTfWxEFUBVA',
    appId: '1:926118704354:web:2df940031c5d9c70779abb',
    messagingSenderId: '926118704354',
    projectId: 'recipeappflutter-17c08',
    authDomain: 'recipeappflutter-17c08.firebaseapp.com',
    storageBucket: 'recipeappflutter-17c08.firebasestorage.app',
    measurementId: 'G-PLMSQ5EYQD',
  );
}
